name: "Deploy to production k8s"

on:
  workflow_call:

    inputs:
      SLACK_PROD_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-deploy-prod ID'
      NAMESPACE:
        type: string
        required: true
        description: 'Namespace in the cluster'
      KUSTOMIZE_OVERLAY:
        type: string
        required: true 
        description: 'Path to Kustomize overlay'
      KUSTOMIZE_ROOT:
        type: string
        required: true
        description: 'Path to Kustomize root'
      IMAGE_TAG:
        type: string
        required: true
        description: 'Image tag to deploy'
      CF_DISTRIBUTION_ID:
        type: string
        required: true
        description: 'CloudFront distribution ID'
      CF_INVALIDATION_PATHS:
        type: string
        required: true
        description: 'CloudFront invalidations paths'
    secrets:
      slack-bot-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:  
  deploy_production:
    runs-on: small-prod-runner
    outputs:
      SLACK_MESSAGE_ID: ${{ steps.gh-deploy-prod.outputs.message_id }}
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}

    steps:
      - name: Check image tag 
        run: | 
          if [[ ! ${{ inputs.IMAGE_TAG }} =~ ^[a-z]+[-] ]] ; then 
            echo 'Invalid Image Tag'
            echo 'must be in {BRANCH_NAME}-{SHA} format'
            echo 'etc: master-2b7f922'
            exit 1
          fi
    
      - name: Set environment variables
        run: |
          TAG=${{ inputs.IMAGE_TAG }}
          echo "TAG=${{ inputs.IMAGE_TAG }}" >> $GITHUB_ENV 
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV

      - name: Notify Slack of Production Deploy
        id: gh-deploy-prod
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
          status: Deploying image ${{ inputs.IMAGE_TAG }} on PROD
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Checkout
        uses: actions/checkout@v1

      # This step causes issues when used as a composite action
      # Therefore the Script is executed from the step directly
      # This could be the subject of the next upgrade
      - name: Inject image tag into files
        run: |
          sudo apt-get update -y
          sudo apt-get install gettext -y
          FILES=(${{ inputs.KUSTOMIZE_ROOT }}/base/* ${{ inputs.KUSTOMIZE_OVERLAY }}/*)
          for FILE in ${FILES[@]}; do
            if [[ -n ${PATTERN} ]] ; then
              envsubst "${PATTERN}" < $FILE > /tmp/envsubst || exit 1
            else
              envsubst < $FILE > /tmp/envsubst || exit 1
            fi
            mv /tmp/envsubst $FILE || exit 1
          done
        env:
          PATTERN: $TAG

      - name: Deploy
        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy@master
        with:
          NAMESPACE: ${{ inputs.NAMESPACE }}
          KUSTOMIZE_OVERLAY: ${{ inputs.KUSTOMIZE_OVERLAY }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v1
        if: ${{ inputs.CF_DISTRIBUTION_ID != '' && inputs.CF_INVALIDATION_PATHS != '' }}
        env:
          DISTRIBUTION: ${{ inputs.CF_DISTRIBUTION_ID }}
          PATHS: ${{ inputs.CF_INVALIDATION_PATHS }}
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}

  slack_report_success:
    runs-on: small-runner
    needs: [deploy_production]
    if: success()
    steps: 
      - name: Notify Slack of Success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_production.outputs.slack_message_id }}
          status: |
            Image Deployed on Production
            Image Tag: ${{ needs.deploy_production.outputs.TAG }}
            Actor: ${{ needs.deploy_production.outputs.GITHUB_ACTOR }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

  slack_report_fail:
    runs-on: small-runner
    needs: [deploy_production]
    if: failure()
    steps: 
      - name: Notify Slack of Failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
          message_id: ${{ needs.deploy_production.outputs.slack_message_id }}
          status: |
            Image Production Deployment Failed 
            Image Tag: ${{ needs.deploy_production.outputs.TAG }}
            Actor: ${{ needs.deploy_production.outputs.GITHUB_ACTOR }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}


